/* eslint-disable */
// Generated by Wrangler by running `wrangler types db/env.d.ts --include-runtime false` (hash: 77e7c518f1686831567b166fc9f4d20f)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	INITIAL_ADMIN_PIN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INITIAL_ADMIN_PIN">> {}
}
